service: api-students

provider:
  name: aws
  runtime: java8
  profile: ${opt:profile, 'uvsy-dev'}
  stage: ${opt:stage, 'dev2'}
  region: ${opt:region, 'sa-east-1'}
  deploymentBucket: ${self:provider.stage}.${self:provider.region}.universy.serverless.deploys
  deploymentPrefix: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}

plugins:
  - serverless-offline

package:
  artifact: build/distributions/${self:service}-1.0.zip


custom:

  # Prune
  prune:
    automatic: true
    number: 3

functions:
  - ${file(./sls/functions/api_student.yml)}

resources:
 - ${file(./sls/resources/profile_dynamo_db_table.yml)}

