Resources:
 ProfileTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:provider.stage}-student-profile
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "alias"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
          - IndexName: AliasIndex
            KeySchema:
              - AttributeName: alias
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
