package app.uvsy.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBGeneratedUuid;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
@DynamoDBTable(tableName = "student-schedules")
public class ScheduleScratch {

    public static final String USER_PROGRAM_INDEX = "UserProgramIndex";

    @DynamoDBHashKey(attributeName = "schedule_scratch_id")
    @DynamoDBGeneratedUuid(value = DynamoDBAutoGenerateStrategy.CREATE)
    private String scheduleScratchId;

    @DynamoDBAttribute(attributeName = "user_id")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = USER_PROGRAM_INDEX, attributeName = "user_id")
    private String userId;

    @DynamoDBAttribute(attributeName = "user_id")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = USER_PROGRAM_INDEX, attributeName = "program_id")
    private String programId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "begin_date")
    private Date beginDate;

    @DynamoDBAttribute(attributeName = "end_date")
    private Date endDate;

    @DynamoDBAttribute(attributeName = "selected_courses")
    private List<SelectedCourse> selectedCourses;

    @DynamoDBAttribute(attributeName = "updated_at")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updatedAt;

    @DynamoDBAttribute(attributeName = "created_at")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

}
